name: Commits

on:
  push:
    branches:
      - '*'

jobs:
  build-app:
    name: Build the application
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build the app
        run: bash ./gradlew assemble

  instrumentation-test:
    name: Run Instrumentation tests
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Make files executable
        run: chmod +x ./gradlew
      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck